# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-np
spec:
  selector:
    app: postgresql-db
  type: NodePort
  externalIPs:
  - 192.168.0.10
  ports:
    - port: 5432
      targetPort: 5432