FROM wso2/wso2am:4.0.0

COPY *.jar /home/wso2carbon/wso2am-4.0.0/repository/components/lib
COPY deployment.toml /home/wso2carbon/wso2am-4.0.0/repository/conf/deployment.toml

#type = "h2"
#url = "jdbc:h2:./repository/database/WSO2AM_DB;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE"
#username = "wso2carbon"
#password = "wso2carbon"