apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso
spec:
  selector:
      matchLabels:
        app: wso
  replicas: 1
  template:
    metadata:
      labels:
        app: wso
    spec:
      containers:
        - name: wso
          image: docker-registry.default.svc:5000/ren-prototype/wso2:latest
          imagePullPolicy: Always
          ports:
          - name: api-https
            containerPort: 8243
          - name: api-http
            containerPort: 8280
          - name: https
            containerPort: 9443
#          volumeMounts:
#          - mountPath: /home/wso2carbon/wso2am-4.0.0/repository/server/
#            name: wso-disk
          resources:
            requests:
              cpu: 200m
              memory: 1200Mi
            limits:
              cpu: 500m
              memory: 2000Mi
      restartPolicy: Always
#      volumes:
#        - name: wso-disk
#          persistentVolumeClaim:
#            claimName: wso-disk
# /home/wso2carbon/wso2am-3.1.0/repository/deployment/server/