apiVersion: apps/v1
kind: Deployment
metadata:
  name: backbuildings
spec:
  selector:
      matchLabels:
        app: backbuildings
  replicas: 1
  template:
    metadata:
      labels:
        app: backbuildings
    spec:
      containers:
        - name: backbuildings
          image: docker-registry.default.svc:5000/ren-prototype/backbuildings:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 170Mi
            limits:
              cpu: 150m
              memory: 275Mi
      restartPolicy: Always