apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
spec:
  selector:
      matchLabels:
        app: ingestion-api
  replicas: 1
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
        - name: ingestion-api
          image: ingestion-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 170Mi
            limits:
              cpu: 350m
              memory: 350Mi
      restartPolicy: Always