apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdr-api
spec:
  selector:
      matchLabels:
        app: hdr-api
  replicas: 1
  template:
    metadata:
      labels:
        app: hdr-api
    spec:
      containers:
        - name: hdr-api
          image: hdr-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 170Mi
            limits:
              cpu: 150m
              memory: 275Mi
      restartPolicy: Always