apiVersion: apps/v1
kind: Deployment
metadata:
  name: backbuildings
spec:
  selector:
      matchLabels:
        app: backbuildings
  replicas: 1
  template:
    metadata:
      labels:
        app: backbuildings
    spec:
      containers:
        - name: backbuildings
          image: backbuildings
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
      restartPolicy: Always