apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
spec:
  selector:
      matchLabels:
        app: data-api
  replicas: 1
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - name: data-api
          image: docker-registry.default.svc:5000/${PROJECT}/data-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 400m
              memory: 825Mi
            limits:
              cpu: 625m
              memory: 1000Mi
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always