/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Area implements Serializable {

    private static final long serialVersionUID = -1133730213;

    private Long   id;
    private String label;
    private String name;
    private Long   assetId;
    private Long   childHeatmapId;
    private Long   dashboardId;
    private Long   parentHeatmapId;

    public Area() {}

    public Area(Area value) {
        this.id = value.id;
        this.label = value.label;
        this.name = value.name;
        this.assetId = value.assetId;
        this.childHeatmapId = value.childHeatmapId;
        this.dashboardId = value.dashboardId;
        this.parentHeatmapId = value.parentHeatmapId;
    }

    public Area(
        Long   id,
        String label,
        String name,
        Long   assetId,
        Long   childHeatmapId,
        Long   dashboardId,
        Long   parentHeatmapId
    ) {
        this.id = id;
        this.label = label;
        this.name = name;
        this.assetId = assetId;
        this.childHeatmapId = childHeatmapId;
        this.dashboardId = dashboardId;
        this.parentHeatmapId = parentHeatmapId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    public Long getChildHeatmapId() {
        return this.childHeatmapId;
    }

    public void setChildHeatmapId(Long childHeatmapId) {
        this.childHeatmapId = childHeatmapId;
    }

    public Long getDashboardId() {
        return this.dashboardId;
    }

    public void setDashboardId(Long dashboardId) {
        this.dashboardId = dashboardId;
    }

    public Long getParentHeatmapId() {
        return this.parentHeatmapId;
    }

    public void setParentHeatmapId(Long parentHeatmapId) {
        this.parentHeatmapId = parentHeatmapId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Area (");

        sb.append(id);
        sb.append(", ").append(label);
        sb.append(", ").append(name);
        sb.append(", ").append(assetId);
        sb.append(", ").append(childHeatmapId);
        sb.append(", ").append(dashboardId);
        sb.append(", ").append(parentHeatmapId);

        sb.append(")");
        return sb.toString();
    }
}
