/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetMeasurement implements Serializable {

    private static final long serialVersionUID = -2023410945;

    private Long measurementId;
    private Long assetId;

    public AssetMeasurement() {}

    public AssetMeasurement(AssetMeasurement value) {
        this.measurementId = value.measurementId;
        this.assetId = value.assetId;
    }

    public AssetMeasurement(
        Long measurementId,
        Long assetId
    ) {
        this.measurementId = measurementId;
        this.assetId = assetId;
    }

    @NotNull
    public Long getMeasurementId() {
        return this.measurementId;
    }

    public void setMeasurementId(Long measurementId) {
        this.measurementId = measurementId;
    }

    @NotNull
    public Long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetMeasurement (");

        sb.append(measurementId);
        sb.append(", ").append(assetId);

        sb.append(")");
        return sb.toString();
    }
}
