/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetDetails implements Serializable {

    private static final long serialVersionUID = 551813273;

    private Long   id;
    private String key;
    private String value;
    private Long   assetId;

    public AssetDetails() {}

    public AssetDetails(AssetDetails value) {
        this.id = value.id;
        this.key = value.key;
        this.value = value.value;
        this.assetId = value.assetId;
    }

    public AssetDetails(
        Long   id,
        String key,
        String value,
        Long   assetId
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.assetId = assetId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 255)
    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @NotNull
    @Size(max = 255)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @NotNull
    public Long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetDetails (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(assetId);

        sb.append(")");
        return sb.toString();
    }
}
