/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetConnection implements Serializable {

    private static final long serialVersionUID = -2015330854;

    private Long assetId;
    private Long connectedAssetId;

    public AssetConnection() {}

    public AssetConnection(AssetConnection value) {
        this.assetId = value.assetId;
        this.connectedAssetId = value.connectedAssetId;
    }

    public AssetConnection(
        Long assetId,
        Long connectedAssetId
    ) {
        this.assetId = assetId;
        this.connectedAssetId = connectedAssetId;
    }

    @NotNull
    public Long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    @NotNull
    public Long getConnectedAssetId() {
        return this.connectedAssetId;
    }

    public void setConnectedAssetId(Long connectedAssetId) {
        this.connectedAssetId = connectedAssetId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetConnection (");

        sb.append(assetId);
        sb.append(", ").append(connectedAssetId);

        sb.append(")");
        return sb.toString();
    }
}
