/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asset implements Serializable {

    private static final long serialVersionUID = 277172571;

    private Long   id;
    private String description;
    private String label;
    private String geoLocation;
    private String name;
    private String uuid;
    private Long   ownerId;
    private Long   parentAssetId;
    private Long   assetTypeId;

    public Asset() {}

    public Asset(Asset value) {
        this.id = value.id;
        this.description = value.description;
        this.label = value.label;
        this.geoLocation = value.geoLocation;
        this.name = value.name;
        this.uuid = value.uuid;
        this.ownerId = value.ownerId;
        this.parentAssetId = value.parentAssetId;
        this.assetTypeId = value.assetTypeId;
    }

    public Asset(
        Long   id,
        String description,
        String label,
        String geoLocation,
        String name,
        String uuid,
        Long   ownerId,
        Long   parentAssetId,
        Long   assetTypeId
    ) {
        this.id = id;
        this.description = description;
        this.label = label;
        this.geoLocation = geoLocation;
        this.name = name;
        this.uuid = uuid;
        this.ownerId = ownerId;
        this.parentAssetId = parentAssetId;
        this.assetTypeId = assetTypeId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Size(max = 255)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Size(max = 255)
    public String getGeoLocation() {
        return this.geoLocation;
    }

    public void setGeoLocation(String geoLocation) {
        this.geoLocation = geoLocation;
    }

    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 255)
    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Long getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    public Long getParentAssetId() {
        return this.parentAssetId;
    }

    public void setParentAssetId(Long parentAssetId) {
        this.parentAssetId = parentAssetId;
    }

    @NotNull
    public Long getAssetTypeId() {
        return this.assetTypeId;
    }

    public void setAssetTypeId(Long assetTypeId) {
        this.assetTypeId = assetTypeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Asset (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(label);
        sb.append(", ").append(geoLocation);
        sb.append(", ").append(name);
        sb.append(", ").append(uuid);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(parentAssetId);
        sb.append(", ").append(assetTypeId);

        sb.append(")");
        return sb.toString();
    }
}
