/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemandRequest implements Serializable {

    private static final long serialVersionUID = 1741726549;

    private Long      id;
    private String    action;
    private String    ext;
    private Timestamp demandRequestStart;
    private Timestamp demandRequestStop;
    private Timestamp updateDate;
    private String    uuid;
    private String    value;
    private Long      assetId;
    private Long      measurementId;
    private Long      measurementTypeId;

    public DemandRequest() {}

    public DemandRequest(DemandRequest value) {
        this.id = value.id;
        this.action = value.action;
        this.ext = value.ext;
        this.demandRequestStart = value.demandRequestStart;
        this.demandRequestStop = value.demandRequestStop;
        this.updateDate = value.updateDate;
        this.uuid = value.uuid;
        this.value = value.value;
        this.assetId = value.assetId;
        this.measurementId = value.measurementId;
        this.measurementTypeId = value.measurementTypeId;
    }

    public DemandRequest(
        Long      id,
        String    action,
        String    ext,
        Timestamp demandRequestStart,
        Timestamp demandRequestStop,
        Timestamp updateDate,
        String    uuid,
        String    value,
        Long      assetId,
        Long      measurementId,
        Long      measurementTypeId
    ) {
        this.id = id;
        this.action = action;
        this.ext = ext;
        this.demandRequestStart = demandRequestStart;
        this.demandRequestStop = demandRequestStop;
        this.updateDate = updateDate;
        this.uuid = uuid;
        this.value = value;
        this.assetId = assetId;
        this.measurementId = measurementId;
        this.measurementTypeId = measurementTypeId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    @Size(max = 255)
    public String getExt() {
        return this.ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

    @NotNull
    public Timestamp getDemandRequestStart() {
        return this.demandRequestStart;
    }

    public void setDemandRequestStart(Timestamp demandRequestStart) {
        this.demandRequestStart = demandRequestStart;
    }

    @NotNull
    public Timestamp getDemandRequestStop() {
        return this.demandRequestStop;
    }

    public void setDemandRequestStop(Timestamp demandRequestStop) {
        this.demandRequestStop = demandRequestStop;
    }

    @NotNull
    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    @NotNull
    @Size(max = 255)
    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @Size(max = 255)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @NotNull
    public Long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    public Long getMeasurementId() {
        return this.measurementId;
    }

    public void setMeasurementId(Long measurementId) {
        this.measurementId = measurementId;
    }

    public Long getMeasurementTypeId() {
        return this.measurementTypeId;
    }

    public void setMeasurementTypeId(Long measurementTypeId) {
        this.measurementTypeId = measurementTypeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DemandRequest (");

        sb.append(id);
        sb.append(", ").append(action);
        sb.append(", ").append(ext);
        sb.append(", ").append(demandRequestStart);
        sb.append(", ").append(demandRequestStop);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(uuid);
        sb.append(", ").append(value);
        sb.append(", ").append(assetId);
        sb.append(", ").append(measurementId);
        sb.append(", ").append(measurementTypeId);

        sb.append(")");
        return sb.toString();
    }
}
