/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Heatmap implements Serializable {

    private static final long serialVersionUID = -882577946;

    private Long   id;
    private String background;
    private String label;
    private String name;
    private Long   userId;

    public Heatmap() {}

    public Heatmap(Heatmap value) {
        this.id = value.id;
        this.background = value.background;
        this.label = value.label;
        this.name = value.name;
        this.userId = value.userId;
    }

    public Heatmap(
        Long   id,
        String background,
        String label,
        String name,
        Long   userId
    ) {
        this.id = id;
        this.background = background;
        this.label = label;
        this.name = name;
        this.userId = userId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getBackground() {
        return this.background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    @Size(max = 255)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Heatmap (");

        sb.append(id);
        sb.append(", ").append(background);
        sb.append(", ").append(label);
        sb.append(", ").append(name);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
