/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationTile implements Serializable {

    private static final long serialVersionUID = -1666188439;

    private Long    id;
    private Boolean featured;
    private String  label;
    private String  layout;
    private String  name;
    private String  props;
    private Long    informationPanelId;
    private Long    informationTileTypeId;

    public InformationTile() {}

    public InformationTile(InformationTile value) {
        this.id = value.id;
        this.featured = value.featured;
        this.label = value.label;
        this.layout = value.layout;
        this.name = value.name;
        this.props = value.props;
        this.informationPanelId = value.informationPanelId;
        this.informationTileTypeId = value.informationTileTypeId;
    }

    public InformationTile(
        Long    id,
        Boolean featured,
        String  label,
        String  layout,
        String  name,
        String  props,
        Long    informationPanelId,
        Long    informationTileTypeId
    ) {
        this.id = id;
        this.featured = featured;
        this.label = label;
        this.layout = layout;
        this.name = name;
        this.props = props;
        this.informationPanelId = informationPanelId;
        this.informationTileTypeId = informationTileTypeId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getFeatured() {
        return this.featured;
    }

    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    @Size(max = 255)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Size(max = 255)
    public String getLayout() {
        return this.layout;
    }

    public void setLayout(String layout) {
        this.layout = layout;
    }

    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 255)
    public String getProps() {
        return this.props;
    }

    public void setProps(String props) {
        this.props = props;
    }

    public Long getInformationPanelId() {
        return this.informationPanelId;
    }

    public void setInformationPanelId(Long informationPanelId) {
        this.informationPanelId = informationPanelId;
    }

    @NotNull
    public Long getInformationTileTypeId() {
        return this.informationTileTypeId;
    }

    public void setInformationTileTypeId(Long informationTileTypeId) {
        this.informationTileTypeId = informationTileTypeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InformationTile (");

        sb.append(id);
        sb.append(", ").append(featured);
        sb.append(", ").append(label);
        sb.append(", ").append(layout);
        sb.append(", ").append(name);
        sb.append(", ").append(props);
        sb.append(", ").append(informationPanelId);
        sb.append(", ").append(informationTileTypeId);

        sb.append(")");
        return sb.toString();
    }
}
