/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationTileMeasurement implements Serializable {

    private static final long serialVersionUID = 1767207993;

    private Long informationTileId;
    private Long measurementId;

    public InformationTileMeasurement() {}

    public InformationTileMeasurement(InformationTileMeasurement value) {
        this.informationTileId = value.informationTileId;
        this.measurementId = value.measurementId;
    }

    public InformationTileMeasurement(
        Long informationTileId,
        Long measurementId
    ) {
        this.informationTileId = informationTileId;
        this.measurementId = measurementId;
    }

    @NotNull
    public Long getInformationTileId() {
        return this.informationTileId;
    }

    public void setInformationTileId(Long informationTileId) {
        this.informationTileId = informationTileId;
    }

    @NotNull
    public Long getMeasurementId() {
        return this.measurementId;
    }

    public void setMeasurementId(Long measurementId) {
        this.measurementId = measurementId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InformationTileMeasurement (");

        sb.append(informationTileId);
        sb.append(", ").append(measurementId);

        sb.append(")");
        return sb.toString();
    }
}
