/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationTileType implements Serializable {

    private static final long serialVersionUID = -942520619;

    private Long   id;
    private String label;
    private String name;

    public InformationTileType() {}

    public InformationTileType(InformationTileType value) {
        this.id = value.id;
        this.label = value.label;
        this.name = value.name;
    }

    public InformationTileType(
        Long   id,
        String label,
        String name
    ) {
        this.id = id;
        this.label = label;
        this.name = name;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InformationTileType (");

        sb.append(id);
        sb.append(", ").append(label);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
