/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasurementType implements Serializable {

    private static final long serialVersionUID = -534202484;

    private Long   id;
    private String baseUnit;
    private String color;
    private Double factor;
    private String label;
    private String metricType;
    private String name;
    private String unit;

    public MeasurementType() {}

    public MeasurementType(MeasurementType value) {
        this.id = value.id;
        this.baseUnit = value.baseUnit;
        this.color = value.color;
        this.factor = value.factor;
        this.label = value.label;
        this.metricType = value.metricType;
        this.name = value.name;
        this.unit = value.unit;
    }

    public MeasurementType(
        Long   id,
        String baseUnit,
        String color,
        Double factor,
        String label,
        String metricType,
        String name,
        String unit
    ) {
        this.id = id;
        this.baseUnit = baseUnit;
        this.color = color;
        this.factor = factor;
        this.label = label;
        this.metricType = metricType;
        this.name = name;
        this.unit = unit;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getBaseUnit() {
        return this.baseUnit;
    }

    public void setBaseUnit(String baseUnit) {
        this.baseUnit = baseUnit;
    }

    @Size(max = 255)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Double getFactor() {
        return this.factor;
    }

    public void setFactor(Double factor) {
        this.factor = factor;
    }

    @Size(max = 255)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Size(max = 255)
    public String getMetricType() {
        return this.metricType;
    }

    public void setMetricType(String metricType) {
        this.metricType = metricType;
    }

    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 255)
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MeasurementType (");

        sb.append(id);
        sb.append(", ").append(baseUnit);
        sb.append(", ").append(color);
        sb.append(", ").append(factor);
        sb.append(", ").append(label);
        sb.append(", ").append(metricType);
        sb.append(", ").append(name);
        sb.append(", ").append(unit);

        sb.append(")");
        return sb.toString();
    }
}
