/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasurementDetails implements Serializable {

    private static final long serialVersionUID = -1469962347;

    private Long   id;
    private String key;
    private String value;
    private Long   measurementId;

    public MeasurementDetails() {}

    public MeasurementDetails(MeasurementDetails value) {
        this.id = value.id;
        this.key = value.key;
        this.value = value.value;
        this.measurementId = value.measurementId;
    }

    public MeasurementDetails(
        Long   id,
        String key,
        String value,
        Long   measurementId
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.measurementId = measurementId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 255)
    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @NotNull
    @Size(max = 255)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @NotNull
    public Long getMeasurementId() {
        return this.measurementId;
    }

    public void setMeasurementId(Long measurementId) {
        this.measurementId = measurementId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MeasurementDetails (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(measurementId);

        sb.append(")");
        return sb.toString();
    }
}
