/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification implements Serializable {

    private static final long serialVersionUID = 298526602;

    private Long      id;
    private Timestamp dateFrom;
    private Timestamp dateTo;
    private String    message;
    private String    type;
    private String    uuid;
    private Long      assetId;
    private Long      dashboardId;

    public Notification() {}

    public Notification(Notification value) {
        this.id = value.id;
        this.dateFrom = value.dateFrom;
        this.dateTo = value.dateTo;
        this.message = value.message;
        this.type = value.type;
        this.uuid = value.uuid;
        this.assetId = value.assetId;
        this.dashboardId = value.dashboardId;
    }

    public Notification(
        Long      id,
        Timestamp dateFrom,
        Timestamp dateTo,
        String    message,
        String    type,
        String    uuid,
        Long      assetId,
        Long      dashboardId
    ) {
        this.id = id;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.message = message;
        this.type = type;
        this.uuid = uuid;
        this.assetId = assetId;
        this.dashboardId = dashboardId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Timestamp getDateFrom() {
        return this.dateFrom;
    }

    public void setDateFrom(Timestamp dateFrom) {
        this.dateFrom = dateFrom;
    }

    public Timestamp getDateTo() {
        return this.dateTo;
    }

    public void setDateTo(Timestamp dateTo) {
        this.dateTo = dateTo;
    }

    @Size(max = 255)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @NotNull
    @Size(max = 255)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Size(max = 255)
    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    public Long getDashboardId() {
        return this.dashboardId;
    }

    public void setDashboardId(Long dashboardId) {
        this.dashboardId = dashboardId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notification (");

        sb.append(id);
        sb.append(", ").append(dateFrom);
        sb.append(", ").append(dateTo);
        sb.append(", ").append(message);
        sb.append(", ").append(type);
        sb.append(", ").append(uuid);
        sb.append(", ").append(assetId);
        sb.append(", ").append(dashboardId);

        sb.append(")");
        return sb.toString();
    }
}
