/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettings implements Serializable {

    private static final long serialVersionUID = 2032368476;

    private Long   id;
    private String settingsJson;
    private Long   userId;

    public UserSettings() {}

    public UserSettings(UserSettings value) {
        this.id = value.id;
        this.settingsJson = value.settingsJson;
        this.userId = value.userId;
    }

    public UserSettings(
        Long   id,
        String settingsJson,
        Long   userId
    ) {
        this.id = id;
        this.settingsJson = settingsJson;
        this.userId = userId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 255)
    public String getSettingsJson() {
        return this.settingsJson;
    }

    public void setSettingsJson(String settingsJson) {
        this.settingsJson = settingsJson;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSettings (");

        sb.append(id);
        sb.append(", ").append(settingsJson);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
