/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles implements Serializable {

    private static final long serialVersionUID = -1586558842;

    private Long      id;
    private String    type;
    private Timestamp updateDate;
    private String    uuid;
    private Long      userId;

    public UserRoles() {}

    public UserRoles(UserRoles value) {
        this.id = value.id;
        this.type = value.type;
        this.updateDate = value.updateDate;
        this.uuid = value.uuid;
        this.userId = value.userId;
    }

    public UserRoles(
        Long      id,
        String    type,
        Timestamp updateDate,
        String    uuid,
        Long      userId
    ) {
        this.id = id;
        this.type = type;
        this.updateDate = updateDate;
        this.uuid = uuid;
        this.userId = userId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 255)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @NotNull
    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    @Size(max = 255)
    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRoles (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(uuid);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
