/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 566926020;

    private Long   id;
    private String name;
    private String uuid;
    private Long   islandId;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.uuid = value.uuid;
        this.islandId = value.islandId;
    }

    public Users(
        Long   id,
        String name,
        String uuid,
        Long   islandId
    ) {
        this.id = id;
        this.name = name;
        this.uuid = uuid;
        this.islandId = islandId;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 255)
    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @NotNull
    public Long getIslandId() {
        return this.islandId;
    }

    public void setIslandId(Long islandId) {
        this.islandId = islandId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(uuid);
        sb.append(", ").append(islandId);

        sb.append(")");
        return sb.toString();
    }
}
