apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-api
spec:
  selector:
      matchLabels:
        app: influx-api
  replicas: 1
  template:
    metadata:
      labels:
        app: influx-api
    spec:
      containers:
        - name: influx-api
          image: docker-registry.default.svc:5000/${PROJECT}/influx-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 400m
              memory: 825Mi
            limits:
              cpu: 525m
              memory: 1000Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/measurement
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 160
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always