apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-api
spec:
  selector:
      matchLabels:
        app: kubeflow-api
  replicas: 1
  template:
    metadata:
      labels:
        app: kubeflow-api
    spec:
      containers:
        - name: kubeflow-api
          image: kubeflow-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 200m
              memory: 275Mi
            limits:
              cpu: 300m
              memory: 525Mi
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always