apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
      matchLabels:
        app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: docker-registry.default.svc:5000/ren-prototype-devops/sonarqube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 200m
              memory: 1200Mi
            limits:
              cpu: 450m
              memory: 1700Mi
      restartPolicy: Always