apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
      matchLabels:
        app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
      restartPolicy: Always