apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak:latest
        imagePullPolicy: Never
        env:
        #https://github.com/bitnami/containers/blob/main/bitnami/keycloak/24/debian-12/rootfs/opt/bitnami/scripts/keycloak-env.sh
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: "postgres"
 #       - name: KC_DB_URL
 #         value: "jdbc:postgresql://postgresql-db-sv:5432/keycloak"
        - name: DB_ADDR
          value: "postgresql-db-sv"
        - name: DB_PORT
          value: "5432"
        - name: DB_SCHEMA
          value: "public"
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        resources:
          requests:
            cpu: 150m
            memory: 500Mi
          limits:
            cpu: 450m
            memory: 650Mi
#        volumeMounts:
#        - name: keycloak-diskc
#          mountPath: /opt/jboss/keycloak/standalone/configuration/
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
      restartPolicy: Always
#      volumes:
#        - name: keycloak-diskc
#          persistentVolumeClaim:
#            claimName: keycloak-disk