# InfluxDB StatefulSet Service
apiVersion: v1
kind: Service
metadata:
    name: influx-db-sv
spec:
    ports:
      - name: influx-db-sv
        port: 8086
        targetPort: 8086
    selector:
        app: influx-db
    type: ClusterIP