const { default: axios } = require("axios");
const API_URL = "http://front-ren-prototype.apps.paas-dev.psnc.pl/api-postgre/1.0/api/measurements/type"

let types = [
    {
    id: "1",
    name: "electricity_power_w",
    label: "Power [W]",
    unit: "W",
    base_unit: "W",
    metric_type: "electricity",
    factor: 1.0,
    color: "#4CAF50",
    },
    {
        id: "6",
        name: "power_kw",
        label: "ower [kW]",
        base_unit: "W",
        unit: "kW",
        metric_type: "electricity",
        factor: 1000,
        color: "#4CAF50",
    },
    {
        id: "7",
        name: "power_mw",
        label: "Power [MW]",
        base_unit: "W",
        unit: "MW",
        metric_type: "electricity",
        factor: 1000000,
        color: "#4CAF50",
    },
    {
      id: "2",
      name: "electricity_energy_wh",
      label: "Energy[Wh]",
      base_unit: "Wh",
      unit: "Wh",
      metric_type: "electricity",
      factor: 1.0,
      color: "#AAAF50",
    },
    {
      id: "3",
      name: "heat_energy_gj",
      label: "Energy [GJ]",
      base_unit: "Wh",
      unit: "GJ",
      metric_type: "heat",
      factor: 0.0000036,
      color: "#4CAF50",
    },
    {
        id: "8",
        name: "energy_kwh",
        label: "Energy [kWh]",
        base_unit: "Wh",
        unit: "kWh",
        metric_type: "heat",
        factor: 1000,
        color: "#4CAF50",
    },
    {
        id: "9",
        name: "energy_mwh",
        label: "Energy [MWh]",
        base_unit: "W",
        unit: "MWh",
        factor: 1000000,
        color: "#4CAF50",
    },
    {
        id: "10",
        name: "voltage_v",
        label: "Voltage [V]",
        base_unit: "V",
        unit: "V",
        factor: 1,
        color: "#4CAF50",
    },
    {
        id: "11",
        name: "voltage_kv",
        label: "Voltage [kV]",
        base_unit: "V",
        unit: "kV",
        factor: 1000,
        color: "#4CAF50",
    },
    {
      id: "4",
      name: "temperature_c",
      label: "Temperature[°C]",
      unit: "°C",
      base_unit: "°C",
      metric_type: "temperature",
      factor: 1.0,
      color: "#4CAF50",
    },
    {
      id: "5",
      name: "ratio_percent",
      label: "Ratio[%]",
      unit: "%",
      base_unit: " %",
      metric_type: "renewability",
      factor: 1.0,
      color: "#4CAF50",
    },
    {
        id: "12",
        name: "co2eq_gperkwh",
        label: "CO2eq [g/kWh]",
        base_unit: "g/kWh",
        unit: "g/kWh",
        factor: 1,
        color: "#4CAF50",
    },
    {
        id: "13",
        name: "co2eq_kgpermwh",
        label: "CO2eq [kg/MWh]",
        base_unit: "g/kWh",
        unit: "kg/MWh",
        factor: 1,
        color: "#4CAF50",
    },
    {
        id: "14",
        name: "co2eq_tgpermwh",
        label: "CO2eq [t/MWh]",
        base_unit: "g/kWh",
        unit: "t/MWh",
        factor: 1000,
        color: "#4CAF50",
    },
    {
        id: "15",
        name: "flow_m3perh",
        label: "Flow [m3/h]",
        base_unit: "m3/h",
        unit: "m3/h",
        factor: 1,
        color: "#4CAF50",
    },
    {
        id: "16",
        name: "flow_m3perh",
        label: "Flow [l/h]",
        base_unit: "m3/h",
        unit: "l/h",
        factor: 0.001,
        color: "#4CAF50",
    },
];

for (let type of types)
    axios.post(API_URL, type,
    {
        headers: { "Content-type": "application/json; charset=UTF-8" },
    }).then(response => console.log(response.data));