
INSERT INTO asset_type 
( id, name, label, renovable ) VALUES
( 1, 'room', 'Room', NULL ),
( 2, 'flat', 'Flat', NULL ),
( 3, 'building', 'Building', NULL ),
( 4, 'energy_island', 'Energy island', NULL ),
( 5, 'generation_plant', 'Generation plant', 50 ),
( 6, 'heat_pump', 'Heat pump', 40 ),
( 7, 'gas_boiler', 'Gas boiler', 0 ),
( 8, 'co-generation_unit', 'Co-generation unit', 0 ),
( 9, 'coal_plant', 'Coal plant', 0 ),
( 10, 'pv_plant', 'PV plant', 100 ),
( 11, 'external_heat_grid', 'External heat grid', NULL ),
( 12, 'external_electricity_grid', 'External electricity grid', NULL ),
( 13, 'solar_thermal_collector', 'Solar thermal collector', 100 ),
( 14, 'steam', 'Steam', NULL ),
( 15, 'district_heating', 'District heating', NULL ),
( 16, 'district_cooling', 'District cooling', NULL ),
( 17, 'electricity', 'Electricity', NULL ),
( 18, 'user', 'User', NULL ),
( 19, 'ev_charging_station', 'Ev charging station', 100 ),
( 20, 'office', 'Office', NULL ),
( 21, 'hvac', 'HVAC', NULL ),
( 22, 'supercomputer', 'Supercomputer', NULL ),
( 23, 'datacenter', 'datacenter', NULL ),
( 24, 'heat_exchange', 'Heat Exchange', NULL ),
( 25, 'battery', 'Battery', NULL ),
( 26, 'wind_farm', 'Wind Farm', 100 ),
( 27, 'Garden', 'garden', NULL ); 
