# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-sv
spec:
  selector:
    app: postgresql-db
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432