# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgresql-db:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          resources:
            requests:
              cpu: 150m
              memory: 150Mi
            limits:
              cpu: 350m
              memory: 250Mi
          # Config from ConfigMap
          envFrom:
          - configMapRef:
              name: postgresql-db-config
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi