apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-info
spec:
  selector:
      matchLabels:
        app: weather-info
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-info
    spec:
      containers:
        - name: weather-info
          image: docker-registry.default.svc:5000/ren-prototype-devops/weather-info:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 50Mi
      restartPolicy: Always