apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: renergetic-ui
  name: renergetic-ui
spec:
  selector:
      matchLabels:
        app: renergetic-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: renergetic-ui
    spec:
      containers:
        - name: renergetic-ui
          image: docker-registry.default.svc:5000/${PROJECT}/renergetic-ui:latest
          imagePullPolicy: Always
          ports:
            - name: api-http
              containerPort: 8080
            - name: api-https
              containerPort: 8443
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 100Mi
      restartPolicy: Always