# Backdb Service
apiVersion: v1
kind: Service
metadata:
  name: renergetic-ui-sv
spec:
  selector:
    app: renergetic-ui
  ports:
    - name: api-http
      port: 8080
      targetPort: 8080
    - name: api-https
      port: 8443
      targetPort: 8443
  type: NodePort