apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdr-api
spec:
  selector:
      matchLabels:
        app: hdr-api
  replicas: 1
  template:
    metadata:
      labels:
        app: hdr-api
    spec:
      containers:
        - name: hdr-api
          image: docker-registry.default.svc:5000/${PROJECT}/hdr-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 200m
              memory: 275Mi
            limits:
              cpu: 250m
              memory: 425Mi
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always