/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test;


import com.renergetic.backdb.model.test.tables.Area;
import com.renergetic.backdb.model.test.tables.Asset;
import com.renergetic.backdb.model.test.tables.AssetDetails;
import com.renergetic.backdb.model.test.tables.AssetType;
import com.renergetic.backdb.model.test.tables.Dashboard;
import com.renergetic.backdb.model.test.tables.DemandRequest;
import com.renergetic.backdb.model.test.tables.Heatmap;
import com.renergetic.backdb.model.test.tables.InformationPanel;
import com.renergetic.backdb.model.test.tables.InformationTile;
import com.renergetic.backdb.model.test.tables.InformationTileType;
import com.renergetic.backdb.model.test.tables.Measurement;
import com.renergetic.backdb.model.test.tables.MeasurementDetails;
import com.renergetic.backdb.model.test.tables.MeasurementType;
import com.renergetic.backdb.model.test.tables.Notification;
import com.renergetic.backdb.model.test.tables.UserRoles;
import com.renergetic.backdb.model.test.tables.UserSettings;
import com.renergetic.backdb.model.test.tables.Users;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AREA_PKEY = Indexes0.AREA_PKEY;
    public static final Index ASSET_PKEY = Indexes0.ASSET_PKEY;
    public static final Index UK_N9MRDC7DMULXF2C4XEGOEAEM3 = Indexes0.UK_N9MRDC7DMULXF2C4XEGOEAEM3;
    public static final Index ASSET_DETAILS_PKEY = Indexes0.ASSET_DETAILS_PKEY;
    public static final Index ASSET_TYPE_PKEY = Indexes0.ASSET_TYPE_PKEY;
    public static final Index UK_FGSMMXSMPTUQ7XUYW2PRYK0YA = Indexes0.UK_FGSMMXSMPTUQ7XUYW2PRYK0YA;
    public static final Index DASHBOARD_PKEY = Indexes0.DASHBOARD_PKEY;
    public static final Index DEMAND_REQUEST_PKEY = Indexes0.DEMAND_REQUEST_PKEY;
    public static final Index UK_25T112VJQD6UBQO2CCT8XI5B7 = Indexes0.UK_25T112VJQD6UBQO2CCT8XI5B7;
    public static final Index HEATMAP_PKEY = Indexes0.HEATMAP_PKEY;
    public static final Index INFORMATION_PANEL_PKEY = Indexes0.INFORMATION_PANEL_PKEY;
    public static final Index UK_1MRGFPPAVW475HTQALGGRB1U9 = Indexes0.UK_1MRGFPPAVW475HTQALGGRB1U9;
    public static final Index INFORMATION_TILE_PKEY = Indexes0.INFORMATION_TILE_PKEY;
    public static final Index INFORMATION_TILE_TYPE_PKEY = Indexes0.INFORMATION_TILE_TYPE_PKEY;
    public static final Index UK_K0CXT6JVNX34TATA3ISQ349FR = Indexes0.UK_K0CXT6JVNX34TATA3ISQ349FR;
    public static final Index MEASUREMENT_PKEY = Indexes0.MEASUREMENT_PKEY;
    public static final Index UK_LRT1JXPJNI5QY14YJ3HKIIU4S = Indexes0.UK_LRT1JXPJNI5QY14YJ3HKIIU4S;
    public static final Index MEASUREMENT_DETAILS_PKEY = Indexes0.MEASUREMENT_DETAILS_PKEY;
    public static final Index MEASUREMENT_TYPE_PKEY = Indexes0.MEASUREMENT_TYPE_PKEY;
    public static final Index UK_2IOYT5KGC8XYN1RC4QDPEFJGG = Indexes0.UK_2IOYT5KGC8XYN1RC4QDPEFJGG;
    public static final Index NOTIFICATION_PKEY = Indexes0.NOTIFICATION_PKEY;
    public static final Index UK_D1TW9N1D2290XHFXV5J9XKKJ5 = Indexes0.UK_D1TW9N1D2290XHFXV5J9XKKJ5;
    public static final Index UK_B7DMEV1H0DV204B3CYSAPFS74 = Indexes0.UK_B7DMEV1H0DV204B3CYSAPFS74;
    public static final Index USER_ROLES_PKEY = Indexes0.USER_ROLES_PKEY;
    public static final Index USER_SETTINGS_PKEY = Indexes0.USER_SETTINGS_PKEY;
    public static final Index UK_6KM2M9I3VJUY36RNVKGJ1L61S = Indexes0.UK_6KM2M9I3VJUY36RNVKGJ1L61S;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AREA_PKEY = Internal.createIndex("area_pkey", Area.AREA, new OrderField[] { Area.ID }, true);
        public static Index ASSET_PKEY = Internal.createIndex("asset_pkey", Asset.ASSET, new OrderField[] { Asset.ID }, true);
        public static Index UK_N9MRDC7DMULXF2C4XEGOEAEM3 = Internal.createIndex("uk_n9mrdc7dmulxf2c4xegoeaem3", Asset.ASSET, new OrderField[] { Asset.UUID }, true);
        public static Index ASSET_DETAILS_PKEY = Internal.createIndex("asset_details_pkey", AssetDetails.ASSET_DETAILS, new OrderField[] { AssetDetails.ID }, true);
        public static Index ASSET_TYPE_PKEY = Internal.createIndex("asset_type_pkey", AssetType.ASSET_TYPE, new OrderField[] { AssetType.ID }, true);
        public static Index UK_FGSMMXSMPTUQ7XUYW2PRYK0YA = Internal.createIndex("uk_fgsmmxsmptuq7xuyw2pryk0ya", AssetType.ASSET_TYPE, new OrderField[] { AssetType.NAME }, true);
        public static Index DASHBOARD_PKEY = Internal.createIndex("dashboard_pkey", Dashboard.DASHBOARD, new OrderField[] { Dashboard.ID }, true);
        public static Index DEMAND_REQUEST_PKEY = Internal.createIndex("demand_request_pkey", DemandRequest.DEMAND_REQUEST, new OrderField[] { DemandRequest.ID }, true);
        public static Index UK_25T112VJQD6UBQO2CCT8XI5B7 = Internal.createIndex("uk_25t112vjqd6ubqo2cct8xi5b7", DemandRequest.DEMAND_REQUEST, new OrderField[] { DemandRequest.UUID }, true);
        public static Index HEATMAP_PKEY = Internal.createIndex("heatmap_pkey", Heatmap.HEATMAP, new OrderField[] { Heatmap.ID }, true);
        public static Index INFORMATION_PANEL_PKEY = Internal.createIndex("information_panel_pkey", InformationPanel.INFORMATION_PANEL, new OrderField[] { InformationPanel.ID }, true);
        public static Index UK_1MRGFPPAVW475HTQALGGRB1U9 = Internal.createIndex("uk_1mrgfppavw475htqalggrb1u9", InformationPanel.INFORMATION_PANEL, new OrderField[] { InformationPanel.UUID }, true);
        public static Index INFORMATION_TILE_PKEY = Internal.createIndex("information_tile_pkey", InformationTile.INFORMATION_TILE, new OrderField[] { InformationTile.ID }, true);
        public static Index INFORMATION_TILE_TYPE_PKEY = Internal.createIndex("information_tile_type_pkey", InformationTileType.INFORMATION_TILE_TYPE, new OrderField[] { InformationTileType.ID }, true);
        public static Index UK_K0CXT6JVNX34TATA3ISQ349FR = Internal.createIndex("uk_k0cxt6jvnx34tata3isq349fr", InformationTileType.INFORMATION_TILE_TYPE, new OrderField[] { InformationTileType.NAME }, true);
        public static Index MEASUREMENT_PKEY = Internal.createIndex("measurement_pkey", Measurement.MEASUREMENT, new OrderField[] { Measurement.ID }, true);
        public static Index UK_LRT1JXPJNI5QY14YJ3HKIIU4S = Internal.createIndex("uk_lrt1jxpjni5qy14yj3hkiiu4s", Measurement.MEASUREMENT, new OrderField[] { Measurement.UUID }, true);
        public static Index MEASUREMENT_DETAILS_PKEY = Internal.createIndex("measurement_details_pkey", MeasurementDetails.MEASUREMENT_DETAILS, new OrderField[] { MeasurementDetails.ID }, true);
        public static Index MEASUREMENT_TYPE_PKEY = Internal.createIndex("measurement_type_pkey", MeasurementType.MEASUREMENT_TYPE, new OrderField[] { MeasurementType.ID }, true);
        public static Index UK_2IOYT5KGC8XYN1RC4QDPEFJGG = Internal.createIndex("uk_2ioyt5kgc8xyn1rc4qdpefjgg", MeasurementType.MEASUREMENT_TYPE, new OrderField[] { MeasurementType.NAME }, true);
        public static Index NOTIFICATION_PKEY = Internal.createIndex("notification_pkey", Notification.NOTIFICATION, new OrderField[] { Notification.ID }, true);
        public static Index UK_D1TW9N1D2290XHFXV5J9XKKJ5 = Internal.createIndex("uk_d1tw9n1d2290xhfxv5j9xkkj5", Notification.NOTIFICATION, new OrderField[] { Notification.UUID }, true);
        public static Index UK_B7DMEV1H0DV204B3CYSAPFS74 = Internal.createIndex("uk_b7dmev1h0dv204b3cysapfs74", UserRoles.USER_ROLES, new OrderField[] { UserRoles.UUID }, true);
        public static Index USER_ROLES_PKEY = Internal.createIndex("user_roles_pkey", UserRoles.USER_ROLES, new OrderField[] { UserRoles.ID }, true);
        public static Index USER_SETTINGS_PKEY = Internal.createIndex("user_settings_pkey", UserSettings.USER_SETTINGS, new OrderField[] { UserSettings.ID }, true);
        public static Index UK_6KM2M9I3VJUY36RNVKGJ1L61S = Internal.createIndex("uk_6km2m9i3vjuy36rnvkgj1l61s", Users.USERS, new OrderField[] { Users.UUID }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.ID }, true);
    }
}
