apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
spec:
  selector:
      matchLabels:
        app: ingestion-api
  replicas: 1
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
        - name: ingestion-api
          image: docker-registry.default.svc:5000/${PROJECT}/ingestion-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 150m
              memory: 275Mi
            limits:
              cpu: 250m
              memory: 525Mi
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always