apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
      matchLabels:
        app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: docker-registry.default.svc:5000/${PROJECT}/sonarqube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
          - name: SONARQUBE_JDBC_URL
            value: "jdbc:postgresql://postgresql-db-sv:5432/devops"
          - name: SONARQUBE_JDBC_USERNAME
            value: devops
          - name: SONARQUBE_JDBC_PASSWORD
            value: renergetic
          resources:
            requests:
              cpu: 200m
              memory: 1200Mi
            limits:
              cpu: 450m
              memory: 1700Mi
          volumeMounts: 
            - mountPath: /opt/sonarqube/data/
              name: sonarqube-data
            - mountPath: /opt/sonarqube/extensions/
              name: sonarqube-extensions
      volumes: 
        - name: sonarqube-data
          persistentVolumeClaim: 
            claimName: sonarqube-data-disk
        - name: sonarqube-extensions
          persistentVolumeClaim: 
            claimName: sonarqube-ext-disk
      restartPolicy: Always