/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asset extends TableImpl<Record> {

    private static final long serialVersionUID = 1387881333;

    /**
     * The reference instance of <code>public.asset</code>
     */
    public static final Asset ASSET = new Asset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.asset.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), ASSET, "");

    /**
     * The column <code>public.asset.description</code>.
     */
    public static final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.VARCHAR(255), ASSET, "");

    /**
     * The column <code>public.asset.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), ASSET, "");

    /**
     * The column <code>public.asset.geo_location</code>.
     */
    public static final TableField<Record, String> GEO_LOCATION = createField(DSL.name("geo_location"), org.jooq.impl.SQLDataType.VARCHAR(255), ASSET, "");

    /**
     * The column <code>public.asset.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), ASSET, "");

    /**
     * The column <code>public.asset.uuid</code>.
     */
    public static final TableField<Record, String> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.VARCHAR(255), ASSET, "");

    /**
     * The column <code>public.asset.owner_id</code>.
     */
    public static final TableField<Record, Long> OWNER_ID = createField(DSL.name("owner_id"), org.jooq.impl.SQLDataType.BIGINT, ASSET, "");

    /**
     * The column <code>public.asset.parent_asset_id</code>.
     */
    public static final TableField<Record, Long> PARENT_ASSET_ID = createField(DSL.name("parent_asset_id"), org.jooq.impl.SQLDataType.BIGINT, ASSET, "");

    /**
     * The column <code>public.asset.asset_type_id</code>.
     */
    public static final TableField<Record, Long> ASSET_TYPE_ID = createField(DSL.name("asset_type_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), ASSET, "");

    /**
     * No further instances allowed
     */
    private Asset() {
        this(DSL.name("asset"), null);
    }

    private Asset(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Asset(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ASSET_PKEY, Indexes.UK_N9MRDC7DMULXF2C4XEGOEAEM3);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Asset.ASSET, "asset_pkey", com.renergetic.backdb.model.test.tables.Asset.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Asset.ASSET, "asset_pkey", com.renergetic.backdb.model.test.tables.Asset.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Asset.ASSET, "uk_n9mrdc7dmulxf2c4xegoeaem3", com.renergetic.backdb.model.test.tables.Asset.UUID)
        );
    }
}
