/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetType extends TableImpl<Record> {

    private static final long serialVersionUID = 2090299396;

    /**
     * The reference instance of <code>public.asset_type</code>
     */
    public static final AssetType ASSET_TYPE = new AssetType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.asset_type.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), ASSET_TYPE, "");

    /**
     * The column <code>public.asset_type.category</code>.
     */
    public static final TableField<Record, String> CATEGORY = createField(DSL.name("category"), org.jooq.impl.SQLDataType.VARCHAR(255), ASSET_TYPE, "");

    /**
     * The column <code>public.asset_type.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), ASSET_TYPE, "");

    /**
     * The column <code>public.asset_type.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), ASSET_TYPE, "");

    /**
     * The column <code>public.asset_type.renovable</code>.
     */
    public static final TableField<Record, Long> RENOVABLE = createField(DSL.name("renovable"), org.jooq.impl.SQLDataType.BIGINT, ASSET_TYPE, "");

    /**
     * No further instances allowed
     */
    private AssetType() {
        this(DSL.name("asset_type"), null);
    }

    private AssetType(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private AssetType(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ASSET_TYPE_PKEY, Indexes.UK_FGSMMXSMPTUQ7XUYW2PRYK0YA);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.AssetType.ASSET_TYPE, "asset_type_pkey", com.renergetic.backdb.model.test.tables.AssetType.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.AssetType.ASSET_TYPE, "asset_type_pkey", com.renergetic.backdb.model.test.tables.AssetType.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.AssetType.ASSET_TYPE, "uk_fgsmmxsmptuq7xuyw2pryk0ya", com.renergetic.backdb.model.test.tables.AssetType.NAME)
        );
    }
}
