/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dashboard extends TableImpl<Record> {

    private static final long serialVersionUID = -1049333977;

    /**
     * The reference instance of <code>public.dashboard</code>
     */
    public static final Dashboard DASHBOARD = new Dashboard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.dashboard.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), DASHBOARD, "");

    /**
     * The column <code>public.dashboard.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), DASHBOARD, "");

    /**
     * The column <code>public.dashboard.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255), DASHBOARD, "");

    /**
     * The column <code>public.dashboard.url</code>.
     */
    public static final TableField<Record, String> URL = createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR(255), DASHBOARD, "");

    /**
     * The column <code>public.dashboard.user_id</code>.
     */
    public static final TableField<Record, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT, DASHBOARD, "");

    /**
     * No further instances allowed
     */
    private Dashboard() {
        this(DSL.name("dashboard"), null);
    }

    private Dashboard(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Dashboard(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DASHBOARD_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Dashboard.DASHBOARD, "dashboard_pkey", com.renergetic.backdb.model.test.tables.Dashboard.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Dashboard.DASHBOARD, "dashboard_pkey", com.renergetic.backdb.model.test.tables.Dashboard.ID)
        );
    }
}
