/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemandRequest extends TableImpl<Record> {

    private static final long serialVersionUID = -682186624;

    /**
     * The reference instance of <code>public.demand_request</code>
     */
    public static final DemandRequest DEMAND_REQUEST = new DemandRequest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.demand_request.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.action</code>.
     */
    public static final TableField<Record, String> ACTION = createField(DSL.name("action"), org.jooq.impl.SQLDataType.VARCHAR(255), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.ext</code>.
     */
    public static final TableField<Record, String> EXT = createField(DSL.name("ext"), org.jooq.impl.SQLDataType.VARCHAR(255), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.demand_request_start</code>.
     */
    public static final TableField<Record, Timestamp> DEMAND_REQUEST_START = createField(DSL.name("demand_request_start"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.demand_request_stop</code>.
     */
    public static final TableField<Record, Timestamp> DEMAND_REQUEST_STOP = createField(DSL.name("demand_request_stop"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.update_date</code>.
     */
    public static final TableField<Record, Timestamp> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.uuid</code>.
     */
    public static final TableField<Record, String> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.value</code>.
     */
    public static final TableField<Record, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR(255), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.asset_id</code>.
     */
    public static final TableField<Record, Long> ASSET_ID = createField(DSL.name("asset_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.measurement_id</code>.
     */
    public static final TableField<Record, Long> MEASUREMENT_ID = createField(DSL.name("measurement_id"), org.jooq.impl.SQLDataType.BIGINT, DEMAND_REQUEST, "");

    /**
     * The column <code>public.demand_request.measurement_type_id</code>.
     */
    public static final TableField<Record, Long> MEASUREMENT_TYPE_ID = createField(DSL.name("measurement_type_id"), org.jooq.impl.SQLDataType.BIGINT, DEMAND_REQUEST, "");

    /**
     * No further instances allowed
     */
    private DemandRequest() {
        this(DSL.name("demand_request"), null);
    }

    private DemandRequest(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private DemandRequest(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEMAND_REQUEST_PKEY, Indexes.UK_25T112VJQD6UBQO2CCT8XI5B7);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.DemandRequest.DEMAND_REQUEST, "demand_request_pkey", com.renergetic.backdb.model.test.tables.DemandRequest.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.DemandRequest.DEMAND_REQUEST, "demand_request_pkey", com.renergetic.backdb.model.test.tables.DemandRequest.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.DemandRequest.DEMAND_REQUEST, "uk_25t112vjqd6ubqo2cct8xi5b7", com.renergetic.backdb.model.test.tables.DemandRequest.UUID)
        );
    }
}
