/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Heatmap extends TableImpl<Record> {

    private static final long serialVersionUID = 472122684;

    /**
     * The reference instance of <code>public.heatmap</code>
     */
    public static final Heatmap HEATMAP = new Heatmap();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.heatmap.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), HEATMAP, "");

    /**
     * The column <code>public.heatmap.background</code>.
     */
    public static final TableField<Record, String> BACKGROUND = createField(DSL.name("background"), org.jooq.impl.SQLDataType.VARCHAR(255), HEATMAP, "");

    /**
     * The column <code>public.heatmap.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), HEATMAP, "");

    /**
     * The column <code>public.heatmap.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255), HEATMAP, "");

    /**
     * The column <code>public.heatmap.user_id</code>.
     */
    public static final TableField<Record, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT, HEATMAP, "");

    /**
     * No further instances allowed
     */
    private Heatmap() {
        this(DSL.name("heatmap"), null);
    }

    private Heatmap(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Heatmap(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HEATMAP_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Heatmap.HEATMAP, "heatmap_pkey", com.renergetic.backdb.model.test.tables.Heatmap.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Heatmap.HEATMAP, "heatmap_pkey", com.renergetic.backdb.model.test.tables.Heatmap.ID)
        );
    }
}
