/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationTile extends TableImpl<Record> {

    private static final long serialVersionUID = 1962551742;

    /**
     * The reference instance of <code>public.information_tile</code>
     */
    public static final InformationTile INFORMATION_TILE = new InformationTile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.information_tile.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), INFORMATION_TILE, "");

    /**
     * The column <code>public.information_tile.featured</code>.
     */
    public static final TableField<Record, Boolean> FEATURED = createField(DSL.name("featured"), org.jooq.impl.SQLDataType.BOOLEAN, INFORMATION_TILE, "");

    /**
     * The column <code>public.information_tile.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), INFORMATION_TILE, "");

    /**
     * The column <code>public.information_tile.layout</code>.
     */
    public static final TableField<Record, String> LAYOUT = createField(DSL.name("layout"), org.jooq.impl.SQLDataType.VARCHAR(255), INFORMATION_TILE, "");

    /**
     * The column <code>public.information_tile.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), INFORMATION_TILE, "");

    /**
     * The column <code>public.information_tile.props</code>.
     */
    public static final TableField<Record, String> PROPS = createField(DSL.name("props"), org.jooq.impl.SQLDataType.VARCHAR(255), INFORMATION_TILE, "");

    /**
     * The column <code>public.information_tile.information_panel_id</code>.
     */
    public static final TableField<Record, Long> INFORMATION_PANEL_ID = createField(DSL.name("information_panel_id"), org.jooq.impl.SQLDataType.BIGINT, INFORMATION_TILE, "");

    /**
     * The column <code>public.information_tile.information_tile_type_id</code>.
     */
    public static final TableField<Record, Long> INFORMATION_TILE_TYPE_ID = createField(DSL.name("information_tile_type_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), INFORMATION_TILE, "");

    /**
     * No further instances allowed
     */
    private InformationTile() {
        this(DSL.name("information_tile"), null);
    }

    private InformationTile(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private InformationTile(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INFORMATION_TILE_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationTile.INFORMATION_TILE, "information_tile_pkey", com.renergetic.backdb.model.test.tables.InformationTile.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationTile.INFORMATION_TILE, "information_tile_pkey", com.renergetic.backdb.model.test.tables.InformationTile.ID)
        );
    }
}
