/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Public;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationTileMeasurement extends TableImpl<Record> {

    private static final long serialVersionUID = 1465391734;

    /**
     * The reference instance of <code>public.information_tile_measurement</code>
     */
    public static final InformationTileMeasurement INFORMATION_TILE_MEASUREMENT = new InformationTileMeasurement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.information_tile_measurement.information_tile_id</code>.
     */
    public static final TableField<Record, Long> INFORMATION_TILE_ID = createField(DSL.name("information_tile_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), INFORMATION_TILE_MEASUREMENT, "");

    /**
     * The column <code>public.information_tile_measurement.measurement_id</code>.
     */
    public static final TableField<Record, Long> MEASUREMENT_ID = createField(DSL.name("measurement_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), INFORMATION_TILE_MEASUREMENT, "");

    /**
     * No further instances allowed
     */
    private InformationTileMeasurement() {
        this(DSL.name("information_tile_measurement"), null);
    }

    private InformationTileMeasurement(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private InformationTileMeasurement(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }
}
