/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationTileType extends TableImpl<Record> {

    private static final long serialVersionUID = 1567981269;

    /**
     * The reference instance of <code>public.information_tile_type</code>
     */
    public static final InformationTileType INFORMATION_TILE_TYPE = new InformationTileType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.information_tile_type.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), INFORMATION_TILE_TYPE, "");

    /**
     * The column <code>public.information_tile_type.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), INFORMATION_TILE_TYPE, "");

    /**
     * The column <code>public.information_tile_type.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), INFORMATION_TILE_TYPE, "");

    /**
     * No further instances allowed
     */
    private InformationTileType() {
        this(DSL.name("information_tile_type"), null);
    }

    private InformationTileType(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private InformationTileType(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INFORMATION_TILE_TYPE_PKEY, Indexes.UK_K0CXT6JVNX34TATA3ISQ349FR);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationTileType.INFORMATION_TILE_TYPE, "information_tile_type_pkey", com.renergetic.backdb.model.test.tables.InformationTileType.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationTileType.INFORMATION_TILE_TYPE, "information_tile_type_pkey", com.renergetic.backdb.model.test.tables.InformationTileType.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationTileType.INFORMATION_TILE_TYPE, "uk_k0cxt6jvnx34tata3isq349fr", com.renergetic.backdb.model.test.tables.InformationTileType.NAME)
        );
    }
}
