/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationPanel extends TableImpl<Record> {

    private static final long serialVersionUID = 315871118;

    /**
     * The reference instance of <code>public.information_panel</code>
     */
    public static final InformationPanel INFORMATION_PANEL = new InformationPanel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.information_panel.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), INFORMATION_PANEL, "");

    /**
     * The column <code>public.information_panel.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), INFORMATION_PANEL, "");

    /**
     * The column <code>public.information_panel.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), INFORMATION_PANEL, "");

    /**
     * The column <code>public.information_panel.uuid</code>.
     */
    public static final TableField<Record, String> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.VARCHAR(255), INFORMATION_PANEL, "");

    /**
     * The column <code>public.information_panel.owner_id</code>.
     */
    public static final TableField<Record, Long> OWNER_ID = createField(DSL.name("owner_id"), org.jooq.impl.SQLDataType.BIGINT, INFORMATION_PANEL, "");

    /**
     * No further instances allowed
     */
    private InformationPanel() {
        this(DSL.name("information_panel"), null);
    }

    private InformationPanel(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private InformationPanel(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INFORMATION_PANEL_PKEY, Indexes.UK_1MRGFPPAVW475HTQALGGRB1U9);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationPanel.INFORMATION_PANEL, "information_panel_pkey", com.renergetic.backdb.model.test.tables.InformationPanel.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationPanel.INFORMATION_PANEL, "information_panel_pkey", com.renergetic.backdb.model.test.tables.InformationPanel.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.InformationPanel.INFORMATION_PANEL, "uk_1mrgfppavw475htqalggrb1u9", com.renergetic.backdb.model.test.tables.InformationPanel.UUID)
        );
    }
}
