/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measurement extends TableImpl<Record> {

    private static final long serialVersionUID = -2058326129;

    /**
     * The reference instance of <code>public.measurement</code>
     */
    public static final Measurement MEASUREMENT = new Measurement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.measurement.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEASUREMENT, "");

    /**
     * The column <code>public.measurement.description</code>.
     */
    public static final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.VARCHAR(255), MEASUREMENT, "");

    /**
     * The column <code>public.measurement.direction</code>.
     */
    public static final TableField<Record, String> DIRECTION = createField(DSL.name("direction"), org.jooq.impl.SQLDataType.VARCHAR(255), MEASUREMENT, "");

    /**
     * The column <code>public.measurement.icon</code>.
     */
    public static final TableField<Record, String> ICON = createField(DSL.name("icon"), org.jooq.impl.SQLDataType.VARCHAR(255), MEASUREMENT, "");

    /**
     * The column <code>public.measurement.label</code>.
     */
    public static final TableField<Record, String> LABEL = createField(DSL.name("label"), org.jooq.impl.SQLDataType.VARCHAR(255), MEASUREMENT, "");

    /**
     * The column <code>public.measurement.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), MEASUREMENT, "");

    /**
     * The column <code>public.measurement.uuid</code>.
     */
    public static final TableField<Record, String> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.VARCHAR(255), MEASUREMENT, "");

    /**
     * The column <code>public.measurement.measurement_type_id</code>.
     */
    public static final TableField<Record, Long> MEASUREMENT_TYPE_ID = createField(DSL.name("measurement_type_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEASUREMENT, "");

    /**
     * No further instances allowed
     */
    private Measurement() {
        this(DSL.name("measurement"), null);
    }

    private Measurement(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Measurement(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEASUREMENT_PKEY, Indexes.UK_LRT1JXPJNI5QY14YJ3HKIIU4S);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Measurement.MEASUREMENT, "measurement_pkey", com.renergetic.backdb.model.test.tables.Measurement.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Measurement.MEASUREMENT, "measurement_pkey", com.renergetic.backdb.model.test.tables.Measurement.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Measurement.MEASUREMENT, "uk_lrt1jxpjni5qy14yj3hkiiu4s", com.renergetic.backdb.model.test.tables.Measurement.UUID)
        );
    }
}
