/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasurementDetails extends TableImpl<Record> {

    private static final long serialVersionUID = 1223691948;

    /**
     * The reference instance of <code>public.measurement_details</code>
     */
    public static final MeasurementDetails MEASUREMENT_DETAILS = new MeasurementDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.measurement_details.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEASUREMENT_DETAILS, "");

    /**
     * The column <code>public.measurement_details.key</code>.
     */
    public static final TableField<Record, String> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), MEASUREMENT_DETAILS, "");

    /**
     * The column <code>public.measurement_details.value</code>.
     */
    public static final TableField<Record, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), MEASUREMENT_DETAILS, "");

    /**
     * The column <code>public.measurement_details.measurement_id</code>.
     */
    public static final TableField<Record, Long> MEASUREMENT_ID = createField(DSL.name("measurement_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEASUREMENT_DETAILS, "");

    /**
     * No further instances allowed
     */
    private MeasurementDetails() {
        this(DSL.name("measurement_details"), null);
    }

    private MeasurementDetails(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private MeasurementDetails(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEASUREMENT_DETAILS_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.MeasurementDetails.MEASUREMENT_DETAILS, "measurement_details_pkey", com.renergetic.backdb.model.test.tables.MeasurementDetails.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.MeasurementDetails.MEASUREMENT_DETAILS, "measurement_details_pkey", com.renergetic.backdb.model.test.tables.MeasurementDetails.ID)
        );
    }
}
