/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification extends TableImpl<Record> {

    private static final long serialVersionUID = 1146082254;

    /**
     * The reference instance of <code>public.notification</code>
     */
    public static final Notification NOTIFICATION = new Notification();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.notification.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), NOTIFICATION, "");

    /**
     * The column <code>public.notification.date_from</code>.
     */
    public static final TableField<Record, Timestamp> DATE_FROM = createField(DSL.name("date_from"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), NOTIFICATION, "");

    /**
     * The column <code>public.notification.date_to</code>.
     */
    public static final TableField<Record, Timestamp> DATE_TO = createField(DSL.name("date_to"), org.jooq.impl.SQLDataType.TIMESTAMP, NOTIFICATION, "");

    /**
     * The column <code>public.notification.message</code>.
     */
    public static final TableField<Record, String> MESSAGE = createField(DSL.name("message"), org.jooq.impl.SQLDataType.VARCHAR(255), NOTIFICATION, "");

    /**
     * The column <code>public.notification.type</code>.
     */
    public static final TableField<Record, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), NOTIFICATION, "");

    /**
     * The column <code>public.notification.uuid</code>.
     */
    public static final TableField<Record, String> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.VARCHAR(255), NOTIFICATION, "");

    /**
     * The column <code>public.notification.asset_id</code>.
     */
    public static final TableField<Record, Long> ASSET_ID = createField(DSL.name("asset_id"), org.jooq.impl.SQLDataType.BIGINT, NOTIFICATION, "");

    /**
     * The column <code>public.notification.dashboard_id</code>.
     */
    public static final TableField<Record, Long> DASHBOARD_ID = createField(DSL.name("dashboard_id"), org.jooq.impl.SQLDataType.BIGINT, NOTIFICATION, "");

    /**
     * No further instances allowed
     */
    private Notification() {
        this(DSL.name("notification"), null);
    }

    private Notification(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Notification(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.NOTIFICATION_PKEY, Indexes.UK_D1TW9N1D2290XHFXV5J9XKKJ5);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Notification.NOTIFICATION, "notification_pkey", com.renergetic.backdb.model.test.tables.Notification.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Notification.NOTIFICATION, "notification_pkey", com.renergetic.backdb.model.test.tables.Notification.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Notification.NOTIFICATION, "uk_d1tw9n1d2290xhfxv5j9xkkj5", com.renergetic.backdb.model.test.tables.Notification.UUID)
        );
    }
}
