/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends TableImpl<Record> {

    private static final long serialVersionUID = 961979110;

    /**
     * The reference instance of <code>public.users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.users.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), USERS, "");

    /**
     * The column <code>public.users.name</code>.
     */
    public static final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255), USERS, "");

    /**
     * The column <code>public.users.uuid</code>.
     */
    public static final TableField<Record, String> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.VARCHAR(255), USERS, "");

    /**
     * The column <code>public.users.island_id</code>.
     */
    public static final TableField<Record, Long> ISLAND_ID = createField(DSL.name("island_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), USERS, "");

    /**
     * No further instances allowed
     */
    private Users() {
        this(DSL.name("users"), null);
    }

    private Users(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Users(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UK_6KM2M9I3VJUY36RNVKGJ1L61S, Indexes.USERS_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Users.USERS, "users_pkey", com.renergetic.backdb.model.test.tables.Users.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Users.USERS, "users_pkey", com.renergetic.backdb.model.test.tables.Users.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.Users.USERS, "uk_6km2m9i3vjuy36rnvkgj1l61s", com.renergetic.backdb.model.test.tables.Users.UUID)
        );
    }
}
