/*
 * This file is generated by jOOQ.
 */
package com.renergetic.backdb.model.test.tables;


import com.renergetic.backdb.model.test.Indexes;
import com.renergetic.backdb.model.test.Public;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles extends TableImpl<Record> {

    private static final long serialVersionUID = -31690376;

    /**
     * The reference instance of <code>public.user_roles</code>
     */
    public static final UserRoles USER_ROLES = new UserRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.user_roles.id</code>.
     */
    public static final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), USER_ROLES, "");

    /**
     * The column <code>public.user_roles.type</code>.
     */
    public static final TableField<Record, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), USER_ROLES, "");

    /**
     * The column <code>public.user_roles.update_date</code>.
     */
    public static final TableField<Record, Timestamp> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), USER_ROLES, "");

    /**
     * The column <code>public.user_roles.uuid</code>.
     */
    public static final TableField<Record, String> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.VARCHAR(255), USER_ROLES, "");

    /**
     * The column <code>public.user_roles.user_id</code>.
     */
    public static final TableField<Record, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), USER_ROLES, "");

    /**
     * No further instances allowed
     */
    private UserRoles() {
        this(DSL.name("user_roles"), null);
    }

    private UserRoles(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private UserRoles(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UK_B7DMEV1H0DV204B3CYSAPFS74, Indexes.USER_ROLES_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.UserRoles.USER_ROLES, "user_roles_pkey", com.renergetic.backdb.model.test.tables.UserRoles.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.UserRoles.USER_ROLES, "user_roles_pkey", com.renergetic.backdb.model.test.tables.UserRoles.ID)
            , Internal.createUniqueKey(com.renergetic.backdb.model.test.tables.UserRoles.USER_ROLES, "uk_b7dmev1h0dv204b3cysapfs74", com.renergetic.backdb.model.test.tables.UserRoles.UUID)
        );
    }
}
