apiVersion: apps/v1
kind: Deployment
metadata:
  name: backdb
spec:
  selector:
      matchLabels:
        app: backdb
  replicas: 1
  template:
    metadata:
      labels:
        app: backdb
    spec:
      containers:
        - name: backdb
          image: docker-registry.default.svc:5000/ren-prototype/backdb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 50m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 250Mi
      restartPolicy: Always