# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: docker-registry.default.svc:5000/${PROJECT}/postgresql-db:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          resources:
            requests:
              cpu: 150m
              memory: 250Mi
            limits:
              cpu: '1'
              memory: 2Gi
          # Config from ConfigMap
          envFrom:
          - configMapRef:
              name: postgresql-db-config
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "postgres", "-d", "postgres", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi