# Keycloak Service
apiVersion: v1
kind: Service
metadata:
  name: keycloak-sv
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  externalIPs:
  - 192.168.0.12
  ports:
  - name: http
    port: 8280
    targetPort: 8080