apiVersion: v1
kind: Service
metadata:
  name: grafana-sv
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort